name: Add Versions PR Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false && contains(github.event.pull_request.labels.*.name, 'status/auto-created')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check PR branch exists
        id: check-branch
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            let branch = github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/${{ github.event.pull_request.head.ref }}"
            })
            console.log(branch)