name: Clean PR Branch

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false && contains(github.event.pull_request.labels.*.name, 'status/auto-created')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check PR branch exists
        id: check-branch
        uses: actions/github-script@v7
        with:
          script: |
            let {status: status} = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/${{ github.event.pull_request.head.ref }}"
            })
            if (status) {
              await core.summary
                .addHeading("PR Branch Found")
                .addRaw("The PR branch was found and will be cleaned up")
                .write();
            } else {
              await core.summary
                .addHeading("PR Branch Not Found")
                .addRaw("The PR branch didn't exist; the action failure can be ignored.")
                .write();
              core.setFailed("Branch not found, nothing to clean. (failure can be ignored)");
            }
