name: Renovate Rebase PR
on:
  pull_request:
    types: [edited]


jobs:
  checkbox-status:
    runs-on: ubuntu-latest
    outputs:
      isChecked: ${{ steps.check-checkbox.outputs.isChecked }}
    steps:
      - name: Check if PR description checkbox is checked
        id: check-checkbox
        uses: actions/github-script@v7
        with:
          script: |
            const prUrl = context.payload.pull_request.html_url;
            const prBody = context.payload.pull_request.body;
            const checkboxPattern = /- \[([ xX])\] <!-- rebase-check -->/;
            const match = prBody.match(checkboxPattern);

            if (match) {
              await core.summary.addRaw(`Rebase checkbox found in [PR comment](prUrl).`, true).write()
              const isChecked = match[1].toLowerCase() === 'x';
              statusText = `Checkbox is ${isChecked ? 'checked' : 'not checked'}`
              await core.summary.addRaw(statusText, true).write()
              core.info(statusText);
              return { isChecked };
            } else {
              core.summary.addRaw("Rebase checkbox not found in PR comment.", true)
              core.setFailed('Checkbox not found in PR description');
            }
  debug:
    needs: checkbox-status
    if: ${{ needs.checkbox-status.outputs.isChecked == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR description checkbox is checked
        id: check-checkbox
        uses: actions/github-script@v7
        with:
          script: |
            await core.summary.addRaw("End step RAN!!").write()