name: Renovate Rebase PR
on:
  pull_request:
    types: [edited]


jobs:
  check-checkbox-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR description checkbox is checked
        id: check-checkbox
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            console.log(prBody)