name: Validate PR
on:
  push:
  pull_request:
  pull_request_review:
    types: [submitted]
  workflow_call:
jobs:
  validate-versions:
    name: "Check kubectl release versions"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: scripts/check-versions.sh